harborAdminPassword: SUSEPR12345
database:
  type: internal
expose:
  ingress:
    hosts:
      core: eu-spr.merckgroup.com
  tls:
    certSource: secret
    secret:
      secretName: sprcert
externalURL: https://eu-spr.merckgroup.com
jobservice:
  jobLoggers:
    - database
persistence:
  imageChartStorage:
    disableredirect: true
    s3:
      bucket: spr
      region: eu-west-1
      accesskey: XXXXXXXXXXXXXXXXX
      regionendpoint: s3scality.merckgroup.com
      secretkey: XXXXXXXXXXXXXXXXX
      secure: false
      v4auth: true
    type: s3
    caBundleSecretName: s3-ca
  persistentVolumeClaim:
    database:
      storageClass: px-postgress
    jobservice:
      jobLog:
        storageClass: px-jobservice
    redis:
      storageClass: px-redis
    trivy:
      storageClass: px-trivy
proxy:
  httpProxy: http://USERNAME:PASSWORD@proxy.eu.merckgroup.com:8080
  httpsProxy: http://USERNAME:PASSWORD@proxy.eu.merckgroup.com:8080
redis:
  internal:
