apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: suc-gitrepo-setup
  namespace: fleet-default
spec:
  branch: main
  paths:
    - system-upgrade-controller/cluster1/plans
  repo: https://github.com/harrisonbc/fleet-examples.git
  targets:
    - clusterName: k3s-test